[workspace]
resolver = "2"
members = ["crates/lvf"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
rust-version = "1.82"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

[profile.release]
lto = "thin"
codegen-units = 1

[profile.dev.package."*"]
opt-level = 2
